FROM alchemy_furnace:python

COPY ./resource/requirements.txt /tmp/requirements.txt
COPY install_python.sh /tmp/install_python.sh

RUN chmod +x /tmp/install_python.sh && \
    ./tmp/install_python.sh
